export const TRANSLATIONS = {
  en: {
    appTitle: "Gains Tracker", exercise: "EXERCISE", date: "DATE", selectPrompt: "Select an exercise...", sets: "SETS", reps: "REPS", trackBy: "TRACK BY", weightOption: "Weight", timeOption: "Time", weightInput: "WEIGHT", timeInput: "DURATION", secOption: "Sec", minOption: "Min", hrOption: "Hours", cancel: "Cancel", save: "Save", update: "Update", history: "History", logWorkout: "Log Workout", chooseExercise: "Choose Exercise", typeNew: "Type new exercise...", deleteConfirmTitle: "Delete Workout", deleteConfirmMsg: "Are you sure you want to remove this?", deleteExerciseMsg: "Delete this exercise from your list?", calendarOverview: "Calendar Overview", close: "Close", filteredTo: "Filtered to:",
    welcome: "Welcome to", cloudSync: "Cloud Sync Enabled", login: "Login / Register", continueOffline: "Continue Offline", email: "Email", password: "Password", submitLogin: "Sign In", back: "Back",
    forgotPassword: "Forgot Password?", resetSentTitle: "Email Sent", resetSentMsg: "Check your email for a password reset link.", resetPrompt: "Please enter your email address first.", errorTitle: "Error", defaultError: "An unexpected error occurred. Please try again.",
    totalCalories: "CALORIES", totalSets: "TOTAL SETS", settings: "Settings", language: "Language", logout: "Log Out", exitOffline: "Exit Offline Mode", dangerZone: "DANGER ZONE", deleteAccountBtn: "Delete Account", deleteAccountConfirmTitle: "Delete Account", deleteAccountConfirmMsg: "This will permanently delete your account and all cloud data. Are you sure?",
    onboardingTitle: "Your Profile", onboardingSub: "We use your bodyweight to scientifically calculate your calories burned using the METs formula.", bodyweight: "Bodyweight", continueBtn: "Let's Go", intensity: "Intensity:", light: "Light", moderate: "Moderate", vigorous: "Vigorous", caloriesBurned: "CALORIES BURNED", myProfile: "My Profile", updateProfile: "Update Profile",
    "auth/invalid-email": "The email address is badly formatted.", "auth/invalid-credential": "No user found or incorrect password."
  },
  nl: {
    appTitle: "Trainings Tracker", exercise: "OEFENING", date: "DATUM", selectPrompt: "Kies een oefening...", sets: "SETS", reps: "HERHALINGEN", trackBy: "BIJHOUDEN IN", weightOption: "Gewicht", timeOption: "Tijd", weightInput: "GEWICHT", timeInput: "DUUR", secOption: "Sec", minOption: "Min", hrOption: "Uren", cancel: "Annuleren", save: "Opslaan", update: "Aanpassen", history: "Geschiedenis", logWorkout: "Training Loggen", chooseExercise: "Kies Oefening", typeNew: "Nieuwe oefening...", deleteConfirmTitle: "Verwijder Training", deleteConfirmMsg: "Weet je zeker dat je dit wilt verwijderen?", deleteExerciseMsg: "Verwijder deze oefening uit de lijst?", calendarOverview: "Kalender Overzicht", close: "Sluiten", filteredTo: "Gefilterd op:",
    welcome: "Welkom bij", cloudSync: "Cloud Sync Geactiveerd", login: "Inloggen / Registreren", continueOffline: "Offline Doorgaan", email: "E-mailadres", password: "Wachtwoord", submitLogin: "Inloggen", back: "Terug",
    forgotPassword: "Wachtwoord Vergeten?", resetSentTitle: "E-mail Verzonden", resetSentMsg: "Controleer je e-mail voor een reset link.", resetPrompt: "Vul eerst je e-mailadres in.", errorTitle: "Fout", defaultError: "Er is een onverwachte fout opgetreden. Probeer het opnieuw.",
    totalCalories: "CALORIEËN", totalSets: "TOTAAL SETS", settings: "Instellingen", language: "Taal", logout: "Uitloggen", exitOffline: "Offline Modus Verlaten", dangerZone: "GEVARENZONE", deleteAccountBtn: "Account Verwijderen", deleteAccountConfirmTitle: "Account Verwijderen", deleteAccountConfirmMsg: "Dit verwijdert je account en alle cloud data permanent. Weet je het zeker?",
    onboardingTitle: "Jouw Profiel", onboardingSub: "We gebruiken je lichaamsgewicht om wetenschappelijk je verbrande calorieën te berekenen.", bodyweight: "Lichaamsgewicht", continueBtn: "Starten", intensity: "Intensiteit:", light: "Licht", moderate: "Gemiddeld", vigorous: "Zwaar", caloriesBurned: "VERBRANDE CALORIEËN", myProfile: "Mijn Profiel", updateProfile: "Profiel Bijwerken",
    "auth/invalid-email": "Het e-mailadres is ongeldig.", "auth/invalid-credential": "Geen gebruiker gevonden of onjuist wachtwoord."
  }
};